# Top Earners in Movie Industry

## Table of Contents

<ul>
    <li><a href="#intro">Introduction</a></li>
    <li><a href="#eda">Exploratory Data Analysis</a></li>
    <li><a href="#conclusion">Conclusion</a></li>
</ul>

<a id="#intro"></a>
## Introduction

> This analysis project is to be done using the imdb movie data. When the analysis is completed, you should be able to find the top 5 highest grossing directors, the top 5 highest grossing movie genres of all time, comparing the revenue of the highest grossing movies and which companies released the most movies. 

> There are 10 columns that will not be needed for the analysis. Use pandas to drop these columns. HINT: Only the columns pertaining to revenue will be needed.

> To get you started, I've already placed the needed code for getting the packages and datafile that you will be using for the project.

In [1]:
import pandas as pd
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('imdb-movies.csv')
df

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/15,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/15,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/15,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/15,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/15,2947,7.3,2015,1.747999e+08,1.385749e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10861,21,tt0060371,0.080598,0,0,The Endless Summer,Michael Hynson|Robert August|Lord 'Tally Ho' B...,NaN,Bruce Brown,NaN,...,"The Endless Summer, by Bruce Brown, is one of ...",95,Documentary,Bruce Brown Films,6/15/66,11,7.4,1966,0.000000e+00,0.000000e+00
10862,20379,tt0060472,0.065543,0,0,Grand Prix,James Garner|Eva Marie Saint|Yves Montand|Tosh...,NaN,John Frankenheimer,Cinerama sweeps YOU into a drama of speed and ...,...,Grand Prix driver Pete Aron is fired by his te...,176,Action|Adventure|Drama,Cherokee Productions|Joel Productions|Douglas ...,12/21/66,20,5.7,1966,0.000000e+00,0.000000e+00
10863,39768,tt0060161,0.065141,0,0,Beregis Avtomobilya,Innokentiy Smoktunovskiy|Oleg Efremov|Georgi Z...,NaN,Eldar Ryazanov,NaN,...,An insurance agent who moonlights as a carthie...,94,Mystery|Comedy,Mosfilm,1/1/66,11,6.5,1966,0.000000e+00,0.000000e+00
10864,21449,tt0061177,0.064317,0,0,"What's Up, Tiger Lily?",Tatsuya Mihashi|Akiko Wakabayashi|Mie Hama|Joh...,NaN,Woody Allen,WOODY ALLEN STRIKES BACK!,...,"In comic Woody Allen's film debut, he took the...",80,Action|Comedy,Benedict Pictures Corp.,11/2/66,22,5.4,1966,0.000000e+00,0.000000e+00
10865,22293,tt0060666,0.035919,19000,0,Manos: The Hands of Fate,Harold P. Warren|Tom Neyman|John Reynolds|Dian...,NaN,Harold P. Warren,It's Shocking! It's Beyond Your Imagination!,...,A family gets lost on the road and stumbles up...,74,Horror,Norm-Iris,11/15/66,15,1.5,1966,1.276423e+05,0.000000e+00

### Drop columns without neccesary information and remove all records with no financial information -- Pay close attention to things that don't tell you anything regarding financial data

In [93]:
yes = df[df['release_year'] >=2005]
yes.head(30)

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/15,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/15,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/15,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/15,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/15,2947,7.3,2015,1.747999e+08,1.385749e+09
5,281957,tt1663202,9.110700,135000000,532950503,The Revenant,Leonardo DiCaprio|Tom Hardy|Will Poulter|Domhn...,http://www.foxmovies.com/movies/the-revenant,Alejandro GonzÃ¡lez IÃ±Ã¡rritu,"(n. One who has returned, as if from the dead.)",...,"In the 1820s, a frontiersman, Hugh Glass, sets...",156,Western|Drama|Adventure|Thriller,Regency Enterprises|Appian Way|CatchPlay|Anony...,12/25/15,3929,7.2,2015,1.241999e+08,4.903142e+08
6,87101,tt1340138,8.654359,155000000,440603537,Terminator Genisys,Arnold Schwarzenegger|Jason Clarke|Emilia Clar...,http://www.terminatormovie.com/,Alan Taylor,Reset the future,...,"The year is 2029. John Connor, leader of the r...",125,Science Fiction|Action|Thriller|Adventure,Paramount Pictures|Skydance Productions,6/23/15,2598,5.8,2015,1.425999e+08,4.053551e+08
7,286217,tt3659388,7.667400,108000000,595380321,The Martian,Matt Damon|Jessica Chastain|Kristen Wiig|Jeff ...,http://www.foxmovies.com/movies/the-martian,Ridley Scott,Bring Him Home,...,"During a manned mission to Mars, Astronaut Mar...",141,Drama|Adventure|Science Fiction,Twentieth Century Fox Film Corporation|Scott F...,9/30/15,4572,7.6,2015,9.935996e+07,5.477497e+08
8,211672,tt2293640,7.404165,74000000,1156730962,Minions,Sandra Bullock|Jon Hamm|Michael Keaton|Allison...,http://www.minionsmovie.com/,Kyle Balda|Pierre Coffin,"Before Gru, they had a history of bad bosses",...,"Minions Stuart, Kevin and Bob are recruited by...",91,Family|Animation|Adventure|Comedy,Universal Pictures|Illumination Entertainment,6/17/15,2893,6.5,2015,6.807997e+07,1.064192e+09
9,150540,tt2096673,6.326804,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,http://movies.disney.com/inside-out,Pete Docter,Meet the little voices inside your head.,...,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,6/9/15,3935,8.0,2015,1.609999e+08,7.854116e+08
10,206647,tt2379713,6.200282,245000000,880674609,Spectre,Daniel Craig|Christoph Waltz|LÃ©a Seydoux|Ralp...,http://www.sonypictures.com/movies/spectre/,Sam Mendes,A Plan No One Escapes,...,A cryptic message from Bondâ€™s past sends him...,148,Action|Adventure|Crime,Columbia Pictures|Danjaq|B24,10/26/15,3254,6.2,2015,2.253999e+08,8.102203e+08
11,76757,tt1617661,6.189369,176000003,183987723,Jupiter Ascending,Mila Kunis|Channing Tatum|Sean Bean|Eddie Redm...,http://www.jupiterascending.com,Lana Wachowski|Lilly Wachowski,Expand your universe.,...,In a universe where human genetic material is ...,124,Science Fiction|Fantasy|Action|Adventure,Village Roadshow Pictures|Dune Entertainment|A...,2/4/15,1937,5.2,2015,1.619199e+08,1.692686e+08
12,264660,tt0470752,6.118847,15000000,36869414,Ex Machina,Domhnall Gleeson|Alicia Vikander|Oscar Isaac|S...,http://exmachina-movie.com/,Alex Garland,There is nothing more human than the will to s...,...,"Caleb, a 26 year old coder at the world's larg...",108,Drama|Science Fiction,DNA Films|Universal Pictures International (UP...,1/21/15,2854,7.6,2015,1.379999e+07,3.391985e+07
13,257344,tt2120120,5.984995,88000000,243637091,Pixels,Adam Sandler|Michelle Monaghan|Peter Dinklage|...,http://www.pixels-movie.com/,Chris Columbus,Game On.,...,Video game experts are recruited by the milita...,105,Action|Comedy|Science Fiction,Columbia Pictures|Happy Madison Productions,7/16/15,1575,5.8,2015,8.095996e+07,2.241460e+08
14,99861,tt2395427,5.944927,280000000,1405035767,Avengers: Age of Ultron,Robert Downey Jr.|Chris Hemsworth|Mark Ruffalo...,http://marvel.com/movies/movie/193/avengers_ag...,Joss Whedon,A New Age Has Come.,...,When Tony Stark tries to jumpstart a dormant p...,141,Action|Adventure|Science Fiction,Marvel Studios|Prime Focus|Revolution Sun Studios,4/22/15,4304,7.4,2015,2.575999e+08,1.292632e+09
15,273248,tt3460252,5.898400,44000000,155760117,The Hateful Eight,Samuel L. Jackson|Kurt Russell|Jennifer Jason ...,http://thehatefuleight.com/,Quentin Tarantino,No one comes up here without a damn good reason.,...,Bounty hunters seek shelter from a raging bliz...,167,Crime|Drama|Mystery|Western,Double Feature Films|The Weinstein Company|Fil...,12/25/15,2389,7.4,2015,4.047998e+07,1.432992e+08
16,260346,tt2446042,5.749758,48000000,325771424,Taken 3,Liam Neeson|Forest Whitaker|Maggie Grace|Famke...,http://www.taken3movie.com/,Olivier Megaton,It Ends Here,...,Ex-government operative Bryan Mills finds his ...,109,Crime|Action|Thriller,Twentieth Century Fox Film Corporation|M6 Film...,1/1/15,1578,6.1,2015,4.415998e+07,2.997096e+08
17,102899,tt0478970,5.573184,130000000,518602163,Ant-Man,Paul Rudd|Michael Douglas|Evangeline Lilly|Cor...,http://marvel.com/movies/movie/180/ant-man,Peyton Reed,Heroes Don't Get Any Bigger,...,Armed with the astonishing ability to shrink i...,115,Science Fiction|Action|Adventure,Marvel Studios,7/14/15,3779,7.0,2015,1.195999e+08,4.771138e+08
18,150689,tt1661199,5.556818,95000000,542351353,Cinderella,Lily James|Cate Blanchett|Richard Madden|Helen...,NaN,Kenneth Branagh,Midnight is just the beginning.,...,"When her father unexpectedly passes away, youn...",112,Romance|Fantasy|Family|Drama,Walt Disney Pictures|Genre Films|Beagle Pug Fi...,3/12/15,1495,6.8,2015,8.739996e+07,4.989630e+08
19,131634,tt1951266,5.476958,160000000,650523427,The Hunger Games: Mockingjay - Part 2,Jennifer Lawrence|Josh Hutcherson|Liam Hemswor...,http://www.thehungergames.movie/,Francis Lawrence,The fire will burn forever.,...,"With the nation of Panem in a full scale war, ...",136,War|Adventure|Science Fiction,Studio Babelsberg|StudioCanal|Lionsgate|Walt D...,11/18/15,2380,6.5,2015,1.471999e+08,5.984813e+08
20,158852,tt1964418,5.462138,190000000,209035668,Tomorrowland,Britt Robertson|George Clooney|Raffey Cassidy|...,http://movies.disney.com/tomorrowland,Brad Bird,Imagine a world where nothing is impossible.,...,"Bound by a shared destiny, a bright, optimisti...",130,Action|Family|Science Fiction|Adventure|Mystery,Walt Disney Pictures|Babieka|A113,5/19/15,1899,6.2,2015,1.747999e+08,1.923127e+08
21,307081,tt1798684,5.337064,30000000,91709827,Southpaw,Jake Gyllenhaal|Rachel McAdams|Forest Whitaker...,NaN,Antoine Fuqua,Believe in Hope.,...,"Billy ""The Great"" Hope, the reigning junior mi...",123,Action|Drama,Escape Artists|Riche-Ludwig Productions,6/15/15,1386,7.3,2015,2.759999e+07,8.437300e+07
22,254128,tt2126355,4.907832,110000000,470490832,San Andreas,Dwayne Johnson|Alexandra Daddario|Carla Gugino...,http://www.sanandreasmovie.com/,Brad Peyton,"A rescue pilot survived an earthquake, this is...",...,In the aftermath of a massive earthquake in Ca...,114,Action|Drama|Thriller,New Line Cinema|Village Roadshow Pictures|Warn...,5/27/15,2060,6.1,2015,1.012000e+08,4.328514e+08
23,216015,tt2322441,4.710402,40000000,569651467,Fifty Shades of Grey,Dakota Johnson|Jamie Dornan|Jennifer Ehle|Eloi...,https://www.facebook.com/fiftyshadesofgreymovie,Sam Taylor-Johnson,Are you curious?,...,When college senior Anastasia Steele steps in ...,125,Drama|Romance,Focus Features|Trigger Street Productions|Mich...,2/11/15,1865,5.3,2015,3.679998e+07,5.240791e+08
24,318846,tt1596363,4.648046,28000000,133346506,The Big Short,Christian Bale|Steve Carell|Ryan Gosling|Brad ...,http://www.thebigshortmovie.com/,Adam McKay,This is a true story.,...,The men who made millions from a global econom...,130,Comedy|Drama,Paramount Pictures|Plan B Entertainment|Regenc...,12/11/15,1545,7.3,2015,2.575999e+07,1.226787e+08
25,177677,tt2381249,4.566713,150000000,682330139,Mission: Impossible - Rogue Nation,Tom Cruise|Jeremy Renner|Simon Pegg|Rebecca Fe...,http://www.missionimpossible.com,Christopher McQuarrie,Desperate Times. Desperate Measures.,...,Ethan and team take on their most impossible m...,131,Action,Paramount Pictures|Skydance Productions|China ...,7/23/15,2349,7.1,2015,1.379999e+08,6.277435e+08
26,214756,tt2637276,4.564549,68000000,215863606,Ted 2,Mark Wahlberg|Seth MacFarlane|Amanda Seyfried|...,NaN,Seth MacFarlane,"Ted is Coming, Again.",...,Newlywed couple Ted and Tami-Lynn want to have...,115,Comedy,Universal Pictures|Media Rights Capital|Fuzzy ...,6/25/15,1666,6.3,2015,6.255997e+07,1.985944e+08
27,207703,tt2802144,4.503789,81000000,403802136,Kingsman: The Secret Service,Taron Egerton|Colin Firth|Samuel L. Jackson|Mi...,http://www.kingsmanmovie.com/,Matthew Vaughn,Manners maketh man.,...,The story of a super-secret spy organization t...,130,Crime|Comedy|Action|Adventure,Twentieth Century Fox Film Corporation|Marv Fi...,1/24/15,3833,7.6,2015,7.451997e+07,3.714978e+08
28,314365,tt1895587,4.062293,20000000,88346473,Spotlight,Mark Ruffalo|Michael Keaton|Rachel McAdams|Lie...,http://www.spotlightthefilm.com,Tom McCarthy,Break the story. Break the silence.,...,The true story of how The Boston Globe uncover...,128,Drama|Thriller|History,Participant Media|Open Road Films|Anonymous Co...,11/6/15,1559,7.8,2015,1.839999e+07,8.127872e+07
29,294254,tt4046784,3.968891,61000000,311256926,Maze Runner: The Scorch Trials,Dylan O'Brien|Kaya Scodelario|Thomas Brodie-Sa...,http://mazerunnermovies.com,Wes Ball,The Maze Was Just the Beginning.,...,Thomas and his fellow Gladers face their great...,132,Action|Science Fiction|Thriller,Gotham Group|Temple Hill Entertainment|TSG Ent...,9/9/15,1849,6.4,2015,5.611998e+07,2.863562e+08

### Data Cleaning

In [180]:
# Delete all records with null, or empty values

#### Here's a helpful hint from my own analysis when I ran this the first time. This may help shed light on what your data set should look like.

#### If I created one record for each the `production_companies` a movie was release under and one record each for `genres`<br>and tried to run calculations, it wouldn't work because for many records, the amount of `production_companies`<br>and `genres` aren't the same, so I'll create 2 dataframes; one w/o a `production_companies` column and one w/o a `genres` columns

In [113]:
# first attempt

# prod = df.groupby(['production_companies', 'release_year']).count()[['original_title']].sort_values(['release_year', 'original_title'], ascending=[0,0])

# def ten_years(row):
#     if row['release_year'] >= 2005:
#         print(prod)

# year = prod.apply(ten_years)
# year

<a id="eda"></a>
## Exploratory Data Analysis

> Use Matplotlib to display your data analysis

### Which production companies released the most movies in the last 10 years? Display the top 5 production companies.

In [112]:
prod = df[df['release_year'] >=2005].groupby('production_companies').count()[['original_title']]

prod.sort_values( 'original_title', ascending=False).head(5)

                         original_title
production_companies
DreamWorks Animation                 26
Marvel Studios                       22
Walt Disney Pictures                 22
Pixar Animation Studios              22
The Asylum                           21

### What 5 movie genres grossed the highest all-time?

In [107]:
gen = df.groupby('genres').sum()[['revenue']].sort_values('revenue', ascending=False).head()
gen

                              revenue
genres
Comedy                    20323889661
Drama                     15107533347
Comedy|Romance            11545724341
Adventure|Fantasy|Action   7597483556
Comedy|Drama|Romance       7251175696

### Who are the top 5 grossing directors?

In [37]:
richdirector = df.groupby('director').sum()[['revenue']].sort_values('revenue', ascending = False).head()
richdirector

                      revenue
director
Steven Spielberg   9018563772
Peter Jackson      6523244659
James Cameron      5841894863
Michael Bay        4917208171
Christopher Nolan  4167548502

### Compare the revenue of the highest grossing movies of all time.

In [104]:
movie = df.groupby(['original_title', 'genres', 'release_year', 'director']).sum()[['revenue']]
movie.sort_values('revenue', ascending=False).head(20)

                                                                                                                                  revenue
original_title                                genres                                    release_year director
Avatar                                        Action|Adventure|Fantasy|Science Fiction  2009         James Cameron             2781505847
Star Wars: The Force Awakens                  Action|Adventure|Science Fiction|Fantasy  2015         J.J. Abrams               2068178225
Titanic                                       Drama|Romance|Thriller                    1997         James Cameron             1845034188
The Avengers                                  Science Fiction|Action|Adventure          2012         Joss Whedon               1519557910
Jurassic World                                Action|Adventure|Science Fiction|Thriller 2015         Colin Trevorrow           1513528810
Furious 7                                     Action|Crime|Thriller                     2015         James Wan                 1506249360
Avengers: Age of Ultron                       Action|Adventure|Science Fiction          2015         Joss Whedon               1405035767
Harry Potter and the Deathly Hallows: Part 2  Adventure|Family|Fantasy                  2011         David Yates               1327817822
Frozen                                        Animation|Adventure|Family                2013         Chris Buck|Jennifer Lee   1274219009
Iron Man 3                                    Action|Adventure|Science Fiction          2013         Shane Black               1215439994
Minions                                       Family|Animation|Adventure|Comedy         2015         Kyle Balda|Pierre Coffin  1156730962
Transformers: Dark of the Moon                Action|Science Fiction|Adventure          2011         Michael Bay               1123746996
The Lord of the Rings: The Return of the King Adventure|Fantasy|Action                  2003         Peter Jackson             1118888979
Skyfall                                       Action|Adventure|Thriller                 2012         Sam Mendes                1108561013
The Net                                       Crime|Drama|Mystery|Thriller|Action       1995         Irwin Winkler             1106279658
The Dark Knight Rises                         Action|Crime|Drama|Thriller               2012         Christopher Nolan         1081041287
Pirates of the Caribbean: Dead Man's Chest    Adventure|Fantasy|Action                  2006         Gore Verbinski            1065659812
Toy Story 3                                   Animation|Family|Comedy                   2010         Lee Unkrich               1063171911
Alice in Wonderland                           Family|Fantasy|Adventure                  2010         Tim Burton                1025467110
Pirates of the Caribbean: On Stranger Tides   Adventure|Action|Fantasy                  2011         Rob Marshall              1021683000

<a id="conclusions"></a>
## Conclusions

> Using the cell below, write a brief conclusion of what you have found from the anaylsis of the data. The Cell below will allow you to write plan text instead of code.

Looks like James Cameron is rolling in the dough with 2 movies in the top 5; Avatar & Titanic